### ISSUE TITLE
В конструкторе `SavingAccount` прописаны не все исключения

### ISSUE THREAD

**Issue by Arina-Morozova** [valeri05/javaqa-team-diplom-2#5]
# Описание
В конструкторе SavingAccount не прописаны исключения для случаев, если:
1. минимальный баланс больше или равен максимального;
2. начальный баланс больше максимального;
3. начальный баланс меньше минимального.

# Локализация дефекта
https://github.com/valeri05/javaqa-team-diplom-2/blob/34d4a1335f9a9ba73ac657fa5a8f79b885a9adce/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/valeri05/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA.
2. Создать объект класса `SavingAccount` с параметрами: `initialBalance`=10_000, `minBalance`=11_000, `maxBalance`=10_000, `rate`=5.
3. Рассчитать процент на остаток.
4. Запустить программу.
5. Посмотреть на вывод в консоли.

*Ожидаемый результат:* выкинется исключение.
*Фактический результат:* конструктор принимает значения и выполняет операцию.

# Тест
https://github.com/valeri05/javaqa-team-diplom-2/blob/6b423a78917af263bb3d366590ded7572ad63907/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L313

# Скриншот
![image](https://github.com/Dina1109/team-project/assets/133106566/92fbe3cb-440e-44f5-953b-ef835f199fc4)

# Окружение
* **Операционная система:** Windows 10.
* **IDE:** IntelliJ IDEA 2023.1.2 (Ultimate Edition).
* **Java:** OpenJDK 11.

**Comment by valeri05** [comment]
# Описание

Исправлено. В конструкторе SavingAccount прописаны исключения для случаев, если:

минимальный баланс больше или равен максимального;
начальный баланс больше максимального;
начальный баланс меньше минимального.

# Локализация дефекта

https://github.com/valeri05/javaqa-team-diplom-2/blob/34d4a1335f9a9ba73ac657fa5a8f79b885a9adce/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/valeri05/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA.
2. Создать объект класса SavingAccount с параметрами: initialBalance=10_000, minBalance=11_000, maxBalance=10_000, rate=5.
3. Рассчитать процент на остаток.
4. Запустить программу.
5. Посмотреть на вывод в консоли.

Ожидаемый результат: выкинется исключение.
Фактический результат: выкинется исключение.

# Тест 

https://github.com/valeri05/javaqa-team-diplom-2/blob/6b423a78917af263bb3d366590ded7572ad63907/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L313

# Скриншот

![image](https://github.com/valeri05/javaqa-team-diplom-2/assets/132645004/69bb80a1-ea5f-49b5-afb7-b1a756c7a5fb)

# Окружение
* **Операционная система:** Windows 10.0
* **IDE:** IntelliJ IDEA 2023.1.2 (Community Edition)
* **Java:** OpenJDK 11
