### ISSUE TITLE
Баланс должен быть больше либо равен минимального баланса в классе `SavingAccount` методе `pay`

### ISSUE THREAD

**Issue by Arina-Morozova** [valeri05/javaqa-team-diplom-2#6]
# Описание
Баланс должен быть больше либо равен минимального баланса.

# Локализация дефекта
https://github.com/valeri05/javaqa-team-diplom-2/blob/6b423a78917af263bb3d366590ded7572ad63907/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/valeri05/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA.
2. Создать объект класса `SavingAccount` с параметрами: `initialBalance`=1_500, `minBalance`=1_000, `maxBalance`=10_000, `rate`=5.
3. Вызвать метод `pay` на сумму 500.
4. Запустить программу.
5. Посмотреть на вывод в консоли.

*Ожидаемый результат:* покупка выполняется.
*Фактический результат:* покупка не выполняется.

# Тест
https://github.com/valeri05/javaqa-team-diplom-2/blob/6b423a78917af263bb3d366590ded7572ad63907/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L67

# Скриншот
![image](https://github.com/Dina1109/team-project/assets/133106566/62bf1f19-bbc0-4de7-a27a-e9e57e684a93)

# Окружение
* **Операционная система:** Windows 10.
* **IDE:** IntelliJ IDEA 2023.1.2 (Ultimate Edition).
* **Java:** OpenJDK 11.

**Comment by valeri05** [comment]
# Описание
Исправлено. Баланс больше либо равен минимальному балансу.

# Локализация дефекта
https://github.com/valeri05/javaqa-team-diplom-2/blob/6b423a78917af263bb3d366590ded7572ad63907/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/valeri05/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA.
2. Создать класс объекта SavingAccountс параметрами: initialBalance=1_500, minBalance=1_000, maxBalance=10_000, rate=5.
3. Вызвать метод pay на сумму 500.
4. Запустить программу.
5. Посмотреть на вывод в консоли.

Ожидаемый результат: покупка состоялась.
Фактический результат: покупка состоялась.

# Тест 
https://github.com/valeri05/javaqa-team-diplom-2/blob/8b475b03b52d2abb1573757e97abec2e282e915f/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L67

# Скриншот
![image](https://github.com/valeri05/javaqa-team-diplom-2/assets/132645004/2a9854e4-3286-448c-b0de-bd7be4fb4636)

# Окружение
* **Операционная система:** Windows 10.0
* **IDE:** IntelliJ IDEA 2023.1.2 (Community Edition)
* **Java:** OpenJDK 11
