### ISSUE TITLE
Баланс становится меньше минимального баланса в классе `SavingAccount` методе `pay`, когда в условии `balance > minBalance` переход на `false`

### ISSUE THREAD

**Issue by Arina-Morozova** [valeri05/javaqa-team-diplom-2#7]
# Описание
Баланс становится меньше минимального баланса в классе `SavingAccount` методе `pay`, когда в условии `balance > minBalance` переход на `false`

# Локализация дефекта
https://github.com/valeri05/javaqa-team-diplom-2/blob/6b423a78917af263bb3d366590ded7572ad63907/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/valeri05/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA.
2. Создать объект класса `SavingAccount` с параметрами: `initialBalance`=500, `minBalance`=1_000, `maxBalance`=10_000, `rate`=5.
3. Вызвать метод `pay` на сумму 300.
4. Запустить программу.
5. Посмотреть на вывод в консоли.

*Ожидаемый результат:* покупка не выполняется.
*Фактический результат:* покупка выполняется.

# Тест
https://github.com/valeri05/javaqa-team-diplom-2/blob/6b423a78917af263bb3d366590ded7572ad63907/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L127

# Скриншот
![image](https://github.com/Dina1109/team-project/assets/133106566/298a642a-89c2-474a-8174-f7dcbf7215a4)

# Окружение
* **Операционная система:** Windows 10.
* **IDE:** IntelliJ IDEA 2023.1.2 (Ultimate Edition).
* **Java:** OpenJDK 11.

**Comment by valeri05** [comment]
# Описание

Метод pay выполняет все условия. Тест "shouldPayAmountIfBalanceLessThanMinBalance" необходимо исправить.

# Локализация дефекта

https://github.com/valeri05/javaqa-team-diplom-2/blob/6b423a78917af263bb3d366590ded7572ad63907/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/valeri05/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA.
2. Создать класс объекта SavingAccountс параметрами: initialBalance=500, minBalance=1_000, maxBalance=10_000, rate=5.
3. Вызвать метод pay на сумму 300.
4. Запустить программу.
5. Посмотреть на вывод в консоли.

Ожидаемый результат: false.
Фактический результат: false.

# Тест 

https://github.com/valeri05/javaqa-team-diplom-2/blob/6b423a78917af263bb3d366590ded7572ad63907/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L127

# Скриншот

![image](https://github.com/valeri05/javaqa-team-diplom-2/assets/132645004/4fcfe8ad-0ee4-4faf-a66a-90b360bab736)

# Окружение

* **Операционная система:** Windows 10.0
* **IDE:** IntelliJ IDEA 2023.1.2 (Community Edition)
* **Java:** OpenJDK 11
