### ISSUE TITLE
В результате успешного пополнения баланс становится равным сумме платежа в классе `SavingAccount` методе `add`

### ISSUE THREAD

**Issue by Arina-Morozova** [valeri05/javaqa-team-diplom-2#8]
# Описание
В результате успешного пополнения баланс становится равным сумме платежа, а должен увеличиться на сумму платежа

# Локализация дефекта
https://github.com/valeri05/javaqa-team-diplom-2/blob/6b423a78917af263bb3d366590ded7572ad63907/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/valeri05/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA.
2. Создать объект класса `SavingAccount` с параметрами: `initialBalance`=2_000, `minBalance`=1_000, `maxBalance`=10_000, `rate`=5.
3. Вызвать метод `add` на сумму 3000.
4. Запустить программу.
5. Посмотреть на вывод в консоли.

*Ожидаемый результат:* баланс изменился в большую сторону на внесённую сумму.
*Фактический результат:* баланс равен внесённой сумме.

# Тест
https://github.com/valeri05/javaqa-team-diplom-2/blob/6b423a78917af263bb3d366590ded7572ad63907/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L9

# Скриншот
![image](https://github.com/Dina1109/team-project/assets/133106566/7edac9f2-b865-490b-9998-3700261cbab2)

# Окружение
* **Операционная система:** Windows 10.
* **IDE:** IntelliJ IDEA 2023.1.2 (Ultimate Edition).
* **Java:** OpenJDK 11.

**Comment by valeri05** [comment]
# Описание

Исправлено. В результате успешного пополнения баланс увеличивается на сумму платежа.

# Локализация дефекта

https://github.com/valeri05/javaqa-team-diplom-2/blob/6b423a78917af263bb3d366590ded7572ad63907/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68

# Шаги воспроизведения

1. Открыть код программы в IDEA.
2. Создать объект класса SavingAccount с параметрами: initialBalance=2_000, minBalance=1_000, maxBalance=10_000, rate=5.
3. Вызвать метод add на сумму 3000.
4. Запустить программу.
5. Посмотреть на вывод в консоли.

Ожидаемый результат: баланс изменился в большую сторону на внесённую сумму.
Фактический результат: баланс изменился в большую сторону на внесённую сумму.

# Тест

https://github.com/valeri05/javaqa-team-diplom-2/blob/6b423a78917af263bb3d366590ded7572ad63907/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L9

# Скриншот

![image](https://github.com/valeri05/javaqa-team-diplom-2/assets/132645004/692451b9-2203-4754-a136-81f4884c5612)

# Окружение

* **Операционная система:** Windows 10.0
* **IDE:** IntelliJ IDEA 2023.1.2 (Community Edition)
* **Java:** OpenJDK 11
